### ISSUE TITLE
Manual Section Links Don't Work

### ISSUE THREAD

**Issue by mem48** [nptscot/nptscot.github.io#231] opened 2024-07-19 09:28 UTC
The manual has # sections that change the URL when you click on the table of contents. But you can't use these to make an external link

For example https://nptscot.github.io/manual/#progressivewebapp

**Comment by Robinlovelace** [comment] 2024-07-19 15:00
That is not expected or usual behaviour so this is a bug. Good spot @mem48, thanks for reporting. Any ideas of the cause @mvl22 ?

**Comment by mvl22** [comment] 2024-07-21 14:47
Fixed in https://github.com/nptscot/nptscot.github.io/pull/232.

**Closed** 2024-07-22 12:55 UTC
