### ISSUE TITLE
Geolocate button has no tooltip

### ISSUE THREAD

**Issue by mem48** [nptscot/nptscot.github.io#229] opened 2024-07-15 11:03 UTC
Another issue from https://placebasedcarboncalculator.github.io/ that carries across to this tool.

@mvl22 added nice tooltips to the map controls that have three different behaviours depending on the button

Expected behavior: On basemap button. New tooltip

![image](https://github.com/user-attachments/assets/45e51dd6-5374-416c-b7f0-b39ee73e08b4)

Slightly odd: On built-in map libre buttons: A second tooltip appears after a few seconds

![image](https://github.com/user-attachments/assets/f3921d46-1361-4a27-bfa4-3c8bd2dd57c7)

Broken: On find my location button: Only the second tooltip appears after a few seconds

![image](https://github.com/user-attachments/assets/c8d515ea-dce9-4337-9164-5a5a2c806ae1)

**Comment by Robinlovelace** [comment] 2024-07-15 12:05
Quick fix @mvl22 ?

**Comment by mvl22** [comment] 2024-07-18 22:33
Thanks - well spotted. I can reproduce.

Have been looking at this but still haven't been able to work out what's going on here. There's some odd mix of title and aria attributes. Running a few more tests...

**Comment by Robinlovelace** [comment] 2024-10-28 09:51
Closing because it no longer needs one. Now, better than a tooltip, the search interface pops up and auto-completes suggestions. Great work in #255, job done I think:

![image](https://github.com/user-attachments/assets/d44cdaa6-7123-4fe2-9123-db1b407466e0)

@mem48 can you confirm this is fixed from your perspective too?

You can test it out here: https://nptscot.github.io

Any further feedback on the web app welcome.

**Comment by mvl22** [comment] 2024-10-28 09:53
No, this was the geolocate button, not the geocoder input.

I'm part-way through fixing this - was working on this yesterday though haven't spent long on it. I think there is possibly a timing issue between Tippy which creates the tooltip UI and the geolocate button, or some oddity in the way the attributes are shown.

**Comment by Robinlovelace** [comment] 2024-10-28 09:56
Oh yes of course... I see this as a low priority: the geolocate button is most important on the device on which tooltips are least likely to be shown, even when working: mobile.

**Comment by mem48** [comment] 2024-10-28 10:06
These tooltips do work on mobile, and people also use the geolocate on desktop. At least I do, as Nominatum search is not great.  So I'd still say it is worth fixing. But agree not top priority.

**Comment by Robinlovelace** [comment] 2024-10-28 13:21
![Screenshot_20241028-104212](https://github.com/user-attachments/assets/509f6121-a36c-4a1d-8214-ab320fa99d26)

**Closed** 2024-10-29 10:21 UTC
Labels: enhancement
